#!/usr/bin/env python3

import re
import csv
from Bio.Seq import Seq

def main():
    # ------------------------------------------------------
    # 1. DEFINE GENE DATA
    # ------------------------------------------------------

    outputdirectory = "C:\\Users\\hoffmannmd\\OneDrive - National Institutes of Health\\00_PROJECTS\\STAT_JAK_HKs_paper_request\\NucleotideSequence\\CRISPR\\FoundCRISPRsites\\DISEASE\\"
    # Window size around each mutation
    window_size = 20

    gene_data = {
        "STAT1": {
            "sequence": (
                "ATGTCTCAGTGGTACGAACTTCAGCAGCTTGACTCAAAATTCCTGGAGCAGGTTCACCAGCTTTATGATGACAGTTTTCCCATGGAAATCAGACAGTACCTGGCACAGTGGTTAGAAAAGCAAGACTGGGAGCACGCTGCCAATGATGTTTCATTTGCCACCATCCGTTTTCATGACCTCCTGTCACAGCTGGATGATCAATATAGTCGCTTTTCTTTGGAGAATAACTTCTTGCTACAGCATAACATAAGGAAAAGCAAGCGTAATCTTCAGGATAATTTTCAGGAAGACCCAATCCAGATGTCTATGATCATTTACAGCTGTCTGAAGGAAGAAAGGAAAATTCTGGAAAACGCCCAGAGATTTAATCAGGCTCAGTCGGGGAATATTCAGAGCACAGTGATGTTAGACAAACAGAAAGAGCTTGACAGTAAAGTCAGAAATGTGAAGGACAAGGTTATGTGTATAGAGCATGAAATCAAGAGCCTGGAAGATTTACAAGATGAATATGACTTCAAATGCAAAACCTTGCAGAACAGAGAACACGAGACCAATGGTGTGGCAAAGAGTGATCAGAAACAAGAACAGCTGTTACTCAAGAAGATGTATTTAATGCTTGACAATAAGAGAAAGGAAGTAGTTCACAAAATAATAGAGTTGCTGAATGTCAACTGAACTTACCCAGAATGCCCTGATTAATGATGAACTAGTGGAGTGGAAGCGGAGACAGCAGAGCGCCTGTATTGGGGGGCCGCCCAATGCTTGCTTGGATCAGCTGCAGAACTGGTTCACTATAGTTGCGGAGAGTCTGCAGCAAGTTCGGCAGCAGCTTAAAAAGTTGGAGGAATTGGAACAGAAATACACCTACGAACATGACCCTATCACAAAAAACAAACAAGTGTTATGGGACCGCACCTTCAGTCTTTTCCAGCAGCTCATTCAGAGCTCGTTTGTGGTGGAAAGACAGCCCTGCATGCCAACGCACCCTCAGAGGCCGCTGGTCTTGAAGACAGGGGTCCAGTTCACTGTGAAGTTGAGACTGTTGGTGAAATTGCAAGAGCTGAATTATAATTTGAAAGTCAAAGTCTTATTTGATAAAGATGTGAATGAGAGAAATACAGTAAAAGGATTTAGGAAGTTCAACATTTTGGGCACGCACACAAAAGTGATGAACATGGAGGAGTCCACCAATGGCAGTCTGGCGGCTGAATTTCGGCACCTGCAATTGAAAGAACAGAAAAATGCTGGCACCAGAACGAATGAGGGTCCTCTCATCGTTACTGAAGAGCTTCACTCCCTTAGTTTTGAAACCCAATTGTGCCAGCCTGGTTTGGTAATTGACCTCGAGACGACCTCTCTGCCCGTTGTGGTGATCTCCAACGTCAGCCAGCTCCCGAGCGGTTGGGCCTCCATCCTTTGGTACAACATGCTGGTGGCGGAACCCAGGAATCTGTCCTTCTTCCTGACTCCACCATGTGCACGATGGGCTCAGCTTTCAGAAGTGCTGAGTTGGCAGTTTTCTTCTGTCACCAAAAGAGGTCTCAATGTGGACCAGCTGAACATGTTGGGAGAGAAGCTTCTTGGTCCTAACGCCAGCCCCGATGGTCTCATTCCGTGGACGAGGTTTTGTAAGGAAAATATAAATGATAAAAATTTTCCCTTCTGGCTTTGGATTGAAAGCATCCTAGAACTCATTAAAAAACACCTGCTCCCTCTCTGGAATGATGGGTGCATCATGGGCTTCATCAGCAAGGAGCGAGAGCGTGCCCTGTTGAAGGACCAGCAGCCGGGGACCTTCCTGCTGCGGTTCAGTGAGAGCTCCCGGGAAGGGGCCATCACATTCACATGGGTGGAGCGGTCCCAGAACGGAGGCGAACCTGACTTCCATGCGGTTGAACCCTACACGAAGAAAGAACTTTCTGCTGTTACTTTCCCTGACATCATTCGCAATTACAAAGTCATGGCTGCTGAGAATATTCCTGAGAATCCCCTGAAGTATCTGTATCCAAATATTGACAAAGACCATGCCTTTGGAAAGTATTACTCCAGGCCAAAGGAAGCACCAGAGCCAATGGAACTTGATGGCCCTAAAGGAACTGGATATATCAAGACTGAGTTGATTTCTGTGTCTGAAGTTCACCCTTCTAGACTTCAGACCACAGACAACCTGCTCCCCATGTCTCCTGAGGAGTTTGACGAGGTGTCTCGGATAGTGGGCTCTGTAGAATTCGACAGTATGATGAACACAGTATAG"  # SHORT placeholder
            ),
            "mutations": [
                ("Val266Ile", 796, 798),
                ("Val455Ile", 1363, 1365),
            ],
        },
        "STAT3": {
            "sequence": (
                "ATGGCCCAATGGAATCAGCTACAGCAGCTTGACACACGGTACCTGGAGCAGCTCCATCAGCTCTACAGTGACAGCTTCCCAATGGAGCTGCGGCAGTTTCTGGCCCCTTGGATTGAGAGTCAAGATTGGGCATATGCGGCCAGCAAAGAATCACATGCCACTTTGGTGTTTCATAATCTCCTGGGAGAGATTGACCAGCAGTATAGCCGCTTCCTGCAAGAGTCGAATGTTCTCTATCAGCACAATCTACGAAGAATCAAGCAGTTTCTTCAGAGCAGGTATCTTGAGAAGCCAATGGAGATTGCCCGGATTGTGGCCCGGTGCCTGTGGGAAGAATCACGCCTTCTACAGACTGCAGCCACTGCGGCCCAGCAAGGGGGCCAGGCCAACCACCCCACAGCAGCCGTGGTGACGGAGAAGCAGCAGATGCTGGAGCAGCACCTTCAGGATGTCCGGAAGAGAGTGCAGGATCTAGAACAGAAAATGAAAGTGGTAGAGAATCTCCAGGATGACTTTGATTTCAACTATAAAACCCTCAAGAGTCAAGGAGACATGCAAGATCTGAATGGAAACAACCAGTCAGTGACCAGGCAGAAGATGCAGCAGCTGGAACAGATGCTCACTGCGCTGGACCAGATGCGGAGAAGCATCGTGAGTGAGCTGGCGGGGCTTTTGTCAGCGATGGAGTACGTGCAGAAAACTCTCACGGACGAGGAGCTGGCTGACTGGAAGAGGCGGCAACAGATTGCCTGCATTGGAGGCCCGCCCAACATCTGCCTAGATCGGCTAGAAAACTGGATAACGTCATTAGCAGAATCTCAACTTCAGACCCGTCAACAAATTAAGAAACTGGAGGAGTTGCAGCAAAAAGTTTCCTACAAAGGGGACCCCATTGTACAGCACCGGCCGATGCTGGAGGAGAGAATCGTGGAGCTGTTTAGAAACTTAATGAAAAGTGCCTTTGTGGTGGAGCGGCAGCCCTGCATGCCCATGCATCCTGACCGGCCCCTCGTCATCAAGACCGGCGTCCAGTTCACTACTAAAGTCAGGTTGCTGGTCAAATTCCCTGAGTTGAATTATCAGCTTAAAATTAAAGTGTGCATTGACAAAGACTCTGGGGACGTTGCAGCTCTCAGAGGATCCCGGAAATTTAACATTCTGGGCACAAACACAAAAGTGATGAACATGGAAGAATCCAACAACGGCAGCCTCTCTGCAGAATTCAAACACTTGACCCTGAGGGAGCAGAGATGTGGGAATGGGGGCCGAGCCAATTGTGATGCTTCCCTGATTGTGACTGAGGAGCTGCACCTGATCACCTTTGAGACCGAGGTGTATCACCAAGGCCTCAAGATTGACCTAGAGACCCACTCCTTGCCAGTTGTGGTGATCTCCAACATCTGTCAGATGCCAAATGCCTGGGCGTCCATCCTGTGGTACAACATGCTGACCAACAATCCCAAGAATGTAAACTTTTTTACCAAGCCCCCAATTGGAACCTGGGATCAAGTGGCCGAGGTCCTGAGCTGGCAGTTCTCCTCCACCACCAAGCGAGGACTGAGCATCGAGCAGCTGACTACACTGGCAGAGAAACTCTTGGGACCTGGTGTGAATTATTCAGGGTGTCAGATCACATGGGCTAAATTTTGCAAAGAAAACATGGCTGGCAAGGGCTTCTCCTTCTGGGTCTGGCTGGACAATATCATTGACCTTGTGAAAAAGTACATCCTGGCCCTTTGGAACGAAGGGTACATCATGGGCTTTATCAGTAAGGAGCGGGAGCGGGCCATCTTGAGCACTAAGCCTCCAGGCACCTTCCTGCTAAGATTCAGTGAAAGCAGCAAAGAAGGAGGCGTCACTTTCACTTGGGTGGAGAAGGACATCAGCGGTAAGACCCAGATCCAGTCCGTGGAACCATACACAAAGCAGCAGCTGAACAACATGTCATTTGCTGAAATCATCATGGGCTATAAGATCATGGATGCTACCAATATCCTGGTGTCTCCACTGGTCTATCTCTATCCTGACATTCCCAAGGAGGAGGCATTCGGAAAGTATTGTCGGCCAGAGAGCCAGGAGCATCCTGAAGCTGACCCAGGTAGCGCTGCCCCATACCTGAAGACCAAGTTTATCTGTGTGACACCAACGACCTGCAGCAATACCATTGACCTGCCGATGTCCCCCCGCACTTTAGATTCATTGATGCAGTTTGGAAATAATGGTGAAGGTGCTGAACCCTCAGCAGGAGGGCAGTTTGAGTCCCTCACCTTTGACATGGAGTTGACCTCGGAGTGCGCTACCTCCCCCATGTGA"  # SHORT placeholder
            ),
            "mutations": [
                ("Ser614Arg", 1840, 1842),
                ("Gly618Arg", 1852, 1854),
                ("Asn647Ile", 1939, 1941),
                ("Asp661Tyr", 1981, 1983),
            ],
        },
        "STAT4": {
            "sequence": (
                "ATGTCTCAGTGGAATCAAGTCCAACAGTTAGAAATCAAGTTTTTGGAGCAGGTGGATCAATTCTATGATGACAACTTTCCCATGGAAATTCGGCATCTGTTGGCCCAATGGATTGAAAATCAAGACTGGGAGGCAGCTTCTAACAATGAAACCATGGCAACGATTCTTCTTCAAAACTTGTTAATACAACTGGATGAACAGTTAGGTCGTGTTTCCAAAGAGAAAAACCTACTCTTGATACACAATCTAAAAAGAATTAGGAAGGTCCTTCAGGGAAAATTTCATGGAAATCCAATGCATGTAGCTGTGGTTATTTCAAACTGTTTAAGGGAAGAGAGGAGAATATTGGCTGCAGCCAACATGCCTGTCCAGGGGCCTCTAGAGAAATCCTTACAAAGTTCTTCAGTTTCAGAAAGACAGAGGAATGTGGAGCACAAAGTGGCTGCCATTAAAAACAGTGTGCAGATGACAGAACAAGATACCAAATACTTAGAAGATCTGCAAGACGAATTTGACTACAGGTATAAAACAATTCAGACAATGGATCAGAGTGACAAGAATAGTGCCATGGTGAATCAGGAAGTTTTGACACTGCAGGAAATGCTTAACAGCCTCGATTTCAAGAGAAAGGAGGCTCTCAGTAAAATGACCCAAATCATCCATGAGACAGACCTGTTAATGAACACCATGCTCATAGAAGAGCTGCAAGACTGGAAGCGGCGGCAGCAAATCGCCTGCATCGGGGGTCCACTCCACAATGGGCTCGACCAGCTTCAGAACTGCTTTACACTATTGGCAGAAAGTCTTTTCCAACTGAGAAGGCAATTGGAGAAACTAGAGGAGCAATCTACCAAAATGACATATGAAGGTGATCCCATTCCAATGCAAAGAACTCACATGCTAGAAAGAGTCACCTTCTTGATCTACAACCTTTTCAAGAACTCATTTGTGGTTGAGCGACAGCCATGTATGCCAACCCACCCTCAGAGGCCGTTGGTACTTAAAACCCTAATTCAGTTCACTGTAAAACTAAGGCTACTAATAAAATTGCCAGAACTAAACTATCAGGTAAAGGTTAAGGCATCAATTGACAAGAATGTTTCAACTCTAAGCAACCGAAGATTTGTACTTTGTGGAACTAATGTCAAAGCCATGTCTATTGAAGAATCTTCCAATGGGAGTCTCTCAGTAGAATTTCGACATTTGCAACCAAAGGAAATGAAGTCCAGTGCTGGAGGTAAAGGAAATGAGGGCTGTCACATGGTGACTGAAGAACTTCATTCCATAACGTTTGAAACACAGATCTGCCTCTATGGCCTGACCATAGATTTGGAGACCAGCTCATTGCCTGTGGTGATGATTTCCAATGTCAGTCAGTTACCTAATGCTTGGGCATCCATCATTTGGTACAACGTGTCAACCAACGATTCCCAGAACTTGGTTTTCTTTAATAATCCTCCACCTGCCACATTGAGTCAACTACTGGAGGTGATGAGCTGGCAGTTTTCATCGTACGTTGGTCGTGGTCTTAACTCAGATCAACTCCATATGCTGGCAGAGAAGCTTACAGTCCAATCTAGCTACAGTGATGGTCACCTCACCTGGGCCAAGTTCTGCAAGGAACATTTACCTGGTAAATCATTTACCTTTTGGACATGGCTTGAAGCAATATTGGATCTAATTAAGAAACACATTCTTCCCCTTTGGATTGATGGGTATGTCATGGGCTTTGTTAGCAAAGAGAAGGAACGGCTGTTGCTAAAGGATAAAATGCCTGGCACCTTTTTATTAAGATTCAGTGAAAGCCATCTCGGAGGAATAACTTTCACCTGGGTGGACCATTCTGAAAGTGGGGAAGTGAGATTCCACTCTGTAGAACCCTACAATAAAGGCCGGTTGTCTGCTCTGCCATTCGCTGACATCCTGCGAGACTACAAAGTTATTATGGCTGAAAACATTCCTGAAAACCCTCTGAAGTACCTATATCCTGACATTCCCAAAGACAAAGCCTTCGGTAAACACTACAGCTCTCAGCCTTGCGAAGTTTCAAGACCAACAGAAAGGGGTGACAAAGGTTATGTTCCTTCTGTTTTTATCCCCATCTCAACAATCCGAAGTGATTCAACAGAGCCACATTCTCCATCAGACCTTCTTCCCATGTCTCCAAGTGTGTATGCGGTGTTGAGAGAAAACCTGAGTCCCACAACAATTGAAACTGCAATGAAGTCTCCTTATTCTGCTGAATGA"
            ),
            "mutations": [
                ("Glu128Val", 382, 384),
                ("Gly618Arg", 1336, 1338),
            ],
        },
        "STAT5B": {
            "sequence": (
                "ATGGCTGTGTGGATACAAGCTCAGCAGCTCCAAGGAGAAGCCCTTCATCAGATGCAAGCGTTATATGGCCAGCATTTTCCCATTGAGGTGCGGCATTATTTATCCCAGTGGATTGAAAGCCAAGCATGGGACTCAGTAGATCTTGATAATCCACAGGAGAACATTAAGGCCACCCAGCTCCTGGAGGGCCTGGTGCAGGAGCTGCAGAAGAAGGCAGAGCACCAGGTGGGGGAAGATGGGTTTTTACTGAAGATCAAGCTGGGGCACTATGCCACACAGCTCCAGAACACGTATGACCGCTGCCCCATGGAGCTGGTCCGCTGCATCCGCCATATATTGTACAATGAACAGAGGTTGGTCCGAGAAGCCAACAATGGTAGCTCTCCAGCTGGAAGCCTTGCTGATGCCATGTCCCAGAAACACCTCCAGATCAACCAGACGTTTGAGGAGCTGCGACTGGTCACGCAGGACACAGAGAATGAGTTAAAAAAGCTGCAGCAGACTCAGGAGTACTTCATCATCCAGTACCAGGAGAGCCTGAGGATCCAAGCTCAGTTTGGCCCGCTGGCCCAGCTGAGCCCCCAGGAGCGTCTGAGCCGGGAGACGGCCCTCCAGCAGAAGCAGGTGTCTCTGGAGGCCTGGTTGCAGCGTGAGGCACAGACACTGCAGCAGTACCGCGTGGAGCTGGCCGAGAAGCACCAGAAGACCCTGCAGCTGCTGCGGAAGCAGCAGACCATCATCCTGGATGACGAGCTGATCCAGTGGAAGCGGCGGCAGCAGCTGGCCGGGAACGGCGGGCCCCCCGAGGGCAGCCTGGACGTGCTACAGTCCTGGTGTGAGAAGTTGGCCGAGATCATCTGGCAGAACCGGCAGCAGATCCGCAGGGCTGAGCACCTCTGCCAGCAGCTGCCCATCCCCGGCCCAGTGGAGGAGATGCTGGCCGAGGTCAACGCCACCATCACGGACATTATCTCAGCCCTGGTGACCAGCACGTTCATCATTGAGAAGCAGCCTCCTCAGGTCCTGAAGACCCAGACCAAGTTTGCAGCCACTGTGCGCCTGCTGGTGGGCGGGAAGCTGAACGTGCACATGAACCCCCCCCAGGTGAAGGCCACCATCATCAGTGAGCAGCAGGCCAAGTCTCTGCTCAAGAACGAGAACACCCGCAATGATTACAGTGGCGAGATCTTGAACAACTGCTGCGTCATGGAGTACCACCAAGCCACAGGCACCCTTAGTGCCCACTTCAGGAATATGTCCCTGAAACGAATTAAGAGGTCAGACCGTCGTGGGGCAGAGTCGGTGACAGAAGAAAAATTTACAATCCTGTTTGAATCCCAGTTCAGTGTTGGTGGAAATGAGCTGGTTTTTCAAGTCAAGACCCTGTCCCTGCCAGTGGTGGTGATCGTTCATGGCAGCCAGGACAACAATGCGACGGCCACTGTTCTCTGGGACAATGCTTTTGCAGAGCCTGGCAGGGTGCCATTTGCCGTGCCTGACAAAGTGCTGTGGCCACAGCTGTGTGAGGCGCTCAACATGAAATTCAAGGCCGAAGTGCAGAGCAACCGGGGCCTGACCAAGGAGAACCTCGTGTTCCTGGCGCAGAAACTGTTCAACAACAGCAGCAGCCACCTGGAGGACTACAGTGGCCTGTCTGTGTCCTGGTCCCAGTTCAACAGGGAGAATTTACCAGGACGGAATTACACTTTCTGGCAATGGTTTGACGGTGTGATGGAAGTGTTAAAAAAACATCTCAAGCCTCATTGGAATGATGGGGCCATTTTGGGGTTTGTAAACAAGCAACAGGCCCATGACCTACTCATTAACAAGCCAGATGGGACCTTCCTCCTGAGATTCAGTGACTCAGAAATTGGCGGCATCACCATTGCTTGGAAGTTTGATTCTCAGGAAAGAATGTTTTGGAATCTGATGCCTTTTACCACCAGAGACTTCTCCATTCGGTCCCTAGCCGACCGCTTGGGAGACTTGAATTACCTTATCTACGTGTTTCCTGATCGGCCAAAAGATGAAGTATACTCCAAATACTACACACCAGTTCCCTGCGAGTCTGCTACTGCTAAAGCTGTTGATGGATACGTGAAGCCACAGATCAAGCAAGTGGTCCCTGAGTTTGTGAACGCATCTGCAGATGCCGGGGGCGGCAGCGCCACGTACATGGACCAGGCCCCCTCCCCAGCTGTGTGTCCCCAGGCTCACTATAACATGTACCCACAGAACCCTGACTCAGTCCTTGACACCGATGGGGACTTCGATCTGGAGGACACAATGGACGTAGCGCGGCGTGTGGAGGAGCTCCTGGGCCGGCCAATGGACAGTCAGTGGATCCCGCACGCACAATCGTGA"
            ),
            "mutations": [
                ("Asn642His", 1924, 1926),
            ],
        },
        "JAK2": {
            "sequence": (
                "ATGGGAATGGCCTGCCTTACGATGACAGAAATGGAGGGAACATCCACCTCTTCTATATATCAGAATGGTGATATTTCTGGAAATGCCAATTCTATGAAGCAAATAGATCCAGTTCTTCAGGTGTATCTTTACCATTCCCTTGGGAAATCTGAGGCAGATTATCTGACCTTTCCATCTGGGGAGTATGTTGCAGAAGAAATCTGTATTGCTGCTTCTAAAGCTTGTGGTATCACACCTGTGTATCATAATATGTTTGCTTTAATGAGTGAAACAGAAAGGATCTGGTATCCACCCAACCATGTCTTCCATATAGATGAGTCAACCAGGCATAATGTACTCTACAGAATAAGATTTTACTTTCCTCGTTGGTATTGCAGTGGCAGCAACAGAGCCTATCGGCATGGAATATCTCGAGGTGCTGAAGCTCCTCTTCTTGATGACTTTGTCATGTCTTACCTCTTTGCTCAGTGGCGGCATGATTTTGTGCACGGATGGATAAAAGTACCTGTGACTCATGAAACACAGGAAGAATGTCTTGGGATGGCAGTGTTAGATATGATGAGAATAGCCAAAGAAAACGATCAAACCCCACTGGCCATCTATAACTCTATCAGCTACAAGACATTCTTACCAAAATGTATTCGAGCAAAGATCCAAGACTATCATATTTTGACAAGGAAGCGAATAAGGTACAGATTTCGCAGATTTATTCAGCAATTCAGCCAATGCAAAGCCACTGCCAGAAACTTGAAACTTAAGTATCTTATAAATCTGGAAACTCTGCAGTCTGCCTTCTACACAGAGAAATTTGAAGTAAAAGAACCTGGAAGTGGTCCTTCAGGTGAGGAGATTTTTGCAACCATTATAATAACTGGAAACGGTGGAATTCAGTGGTCAAGAGGGAAACATAAAGAAAGTGAGACACTGACAGAACAGGATTTACAGTTATATTGCGATTTTCCTAATATTATTGATGTCAGTATTAAGCAAGCAAACCAAGAGGGTTCAAATGAAAGCCGAGTTGTAACTATCCATAAGCAAGATGGTAAAAATCTGGAAATTGAACTTAGCTCATTAAGGGAAGCTTTGTCTTTCGTGTCATTAATTGATGGATATTATAGATTAACTGCAGATGCACATCATTACCTCTGTAAAGAAGTAGCACCTCCAGCCGTGCTTGAAAATATACAAAGCAACTGTCATGGCCCAATTTCGATGGATTTTGCCATTAGTAAACTGAAGAAAGCAGGTAATCAGACTGGACTGTATGTACTTCGATGCAGTCCTAAGGACTTTAATAAATATTTTTTGACTTTTGCTGTCGAGCGAGAAAATGTCATTGAATATAAACACTGTTTGATTACAAAAAATGAGAATGAAGAGTACAACCTCAGTGGGACAAAGAAGAACTTCAGCAGTCTTAAAGATCTTTTGAATTGTTACCAGATGGAAACTGTTCGCTCAGACAATATAATTTTCCAGTTTACTAAATGCTGTCCCCCAAAGCCAAAAGATAAATCAAACCTTCTAGTCTTCAGAACGAATGGTGTTTCTGATGTACCAACCTCACCAACATTACAGAGGCCTACTCATATGAACCAAATGGTGTTTCACAAAATCAGAAATGAAGATTTGATATTTAATGAAAGCCTTGGCCAAGGCACTTTTACAAAGATTTTTAAAGGCGTACGAAGAGAAGTAGGAGACTACGGTCAACTGCATGAAACAGAAGTTCTTTTAAAAGTTCTGGATAAAGCACACAGAAACTATTCAGAGTCTTTCTTTGAAGCAGCAAGTATGATGAGCAAGCTTTCTCACAAGCATTTGGTTTTAAATTATGGAGTATGTGTCTGTGGAGACGAGAATATTCTGGTTCAGGAGTTTGTAAAATTTGGATCACTAGATACATATCTGAAAAAGAATAAAAATTGTATAAATATATTATGGAAACTTGAAGTTGCTAAACAGTTGGCATGGGCCATGCATTTTCTAGAAGAAAACACCCTTATTCATGGGAATGTATGTGCCAAAAATATTCTGCTTATCAGAGAAGAAGACAGGAAGACAGGAAATCCTCCTTTCATCAAACTTAGTGATCCTGGCATTAGTATTACAGTTTTGCCAAAGGACATTCTTCAGGAGAGAATACCATGGGTACCACCTGAATGCATTGAAAATCCTAAAAATTTAAATTTGGCAACAGACAAATGGAGTTTTGGTACCACTTTGTGGGAAATCTGCAGTGGAGGAGATAAACCTCTAAGTGCTCTGGATTCTCAAAGAAAGCTACAATTTTATGAAGATAGGCATCAGCTTCCTGCACCAAAGTGGGCAGAATTAGCAAACCTTATAAATAATTGTATGGATTATGAACCAGATTTCAGGCCTTCTTTCAGAGCCATCATACGAGATCTTAACAGTTTGTTTACTCCAGATTATGAACTATTAACAGAAAATGACATGTTACCAAATATGAGGATAGGTGCCCTGGGGTTTTCTGGTGCCTTTGAAGACCGGGATCCTACACAGTTTGAAGAGAGACATTTGAAATTTCTACAGCAACTTGGCAAGGGTAATTTTGGGAGTGTGGAGATGTGCCGGTATGACCCTCTACAGGACAACACTGGGGAGGTGGTCGCTGTAAAAAAGCTTCAGCATAGTACTGAAGAGCACCTAAGAGACTTTGAAAGGGAAATTGAAATCCTGAAATCCCTACAGCATGACAACATTGTAAAGTACAAGGGAGTGTGCTACAGTGCTGGTCGGCGTAATCTAAAATTAATTATGGAATATTTACCATATGGAAGTTTACGAGACTATCTTCAAAAACATAAAGAACGGATAGATCACATAAAACTTCTGCAGTACACATCTCAGATATGCAAGGGTATGGAGTATCTTGGTACAAAAAGGTATATCCACAGGGATCTGGCAACGAGAAATATATTGGTGGAGAACGAGAACAGAGTTAAAATTGGAGATTTTGGGTTAACCAAAGTCTTGCCACAAGACAAAGAATACTATAAAGTAAAAGAACCTGGTGAAAGTCCCATATTCTGGTATGCTCCAGAATCACTGACAGAGAGCAAGTTTTCTGTGGCCTCAGATGTTTGGAGCTTTGGAGTGGTTCTGTATGAACTTTTCACATACATTGAGAAGAGTAAAAGTCCACCAGCGGAATTTATGCGTATGATTGGCAATGACAAACAAGGACAGATGATCGTGTTCCATTTGATAGAACTTTTGAAGAATAATGGAAGATTACCAAGACCAGATGGATGCCCAGATGAGATCTATATGATCATGACAGAATGCTGGAACAATAATGTAAATCAACGCCCCTCCTTTAGGGATCTAGCTCTTCGAGTGGATCAAATAAGGGATAACATGGCTGGATGA"
            ),
            "mutations": [
                ("Arg564Leu", 1690, 1692),
                ("Gly571Ser", 1711, 1713),
                ("Val617Phe/Val617Ile", 1849, 1851),
                ("Arg683Gly/Arg683Ser", 2047, 2049),
                ("Ile724Thr", 2170, 2172),
                ("Glu846Asp", 2536, 2538),
                ("Arg1063His", 3187, 3189),
                ("Asn1108Ser", 3322, 3324)
            ],
        },
        "JAK3": {
            "sequence": (
                "ATGGCACCTCCAAGTGAAGAGACGCCCCTGATCCCTCAGCGTTCATGCAGCCTCTTGTCCACGGAGGCTGGTGCCCTGCATGTGCTGCTGCCCGCTCGGGGCCCCGGGCCCCCCCAGCGCCTATCTTTCTCCTTTGGGGACCACTTGGCTGAGGACCTGTGCGTGCAGGCTGCCAAGGCCAGCGGCATCCTGCCTGTGTACCACTCCCTCTTTGCTCTGGCCACGGAGGACCTGTCCTGCTGGTTCCCCCCGAGCCACATCTTCTCCGTGGAGGATGCCAGCACCCAAGTCCTGCTGTACAGGATTCGCTTTTACTTCCCCAATTGGTTTGGGCTGGAGAAGTGCCACCGCTTCGGGCTACGCAAGGATTTGGCCAGTGCTATCCTTGACCTGCCAGTCCTGGAGCACCTCTTTGCCCAGCACCGCAGTGACCTGGTGAGTGGGCGCCTCCCCGTGGGCCTCAGTCTCAAGGAGCAGGGTGAGTGTCTCAGCCTGGCCGTGTTGGACCTGGCCCGGATGGCGCGAGAGCAGGCCCAGCGGCCGGGAGAGCTGCTGAAGACTGTCAGCTACAAGGCCTGCCTACCCCCAAGCCTGCGCGACCTGATCCAGGGCCTGAGCTTCGTGACGCGGAGGCGTATTCGGAGGACGGTGCGCAGAGCCCTGCGCCGCGTGGCCGCCTGCCAGGCAGACCGGCACTCGCTCATGGCCAAGTACATCATGGACCTGGAGCGGCTGGATCCAGCCGGGGCCGCCGAGACCTTCCACGTGGGCCTCCCTGGGGCCCTTGGTGGCCACGACGGGCTGGGGCTGCTCCGCGTGGCTGGTGACGGCGGCATCGCCTGGACCCAGGGAGAACAGGAGGTCCTCCAGCCCTTCTGCGACTTTCCAGAAATCGTAGACATTAGCATCAAGCAGGCCCCGCGCGTTGGCCCGGCCGGAGAGCACCGCCTGGTCACTGTTACCAGGACAGACAACCAGATTTTAGAGGCCGAGTTCCCAGGGCTGCCCGAGGCTCTGTCGTTCGTGGCGCTCGTGGACGGCTACTTCCGGCTGACCACGGACTCCCAGCACTTCTTCTGCAAGGAGGTGGCACCGCCGAGGCTGCTGGAGGAAGTGGCCGAGCAGTGCCACGGCCCCATCACTCTGGACTTTGCCATCAACAAGCTCAAGACTGGGGGCTCACGTCCTGGCTCCTATGTTCTCCGCCGCAGCCCCCAGGACTTTGACAGCTTCCTCCTCACTGTCTGTGTCCAGAACCCCCTTGGTCCTGATTATAAGGGCTGCCTCATCCGGCGCAGCCCCACAGGAACCTTCCTTCTGGTTGGCCTCAGCCGACCCCACAGCAGTCTTCGAGAGCTCCTGGCAACCTGCTGGGATGGGGGGCTGCACGTAGATGGGGTGGCAGTGACCCTCACTTCCTGCTGTATCCCCAGACCCAAAGAAAAGTCCAACCTGATCGTGGTCCAGAGAGGTCACAGCCCACCCACATCATCCTTGGTTCAGCCCCAATCCCAATACCAGCTGAGTCAGATGACATTTCACAAGATCCCTGCTGACAGCCTGGAGTGGCATGAGAACCTGGGCCATGGGTCCTTCACCAAGATTTACCGGGGCTGTCGCCATGAGGTGGTGGATGGGGAGGCCCGAAAGACAGAGGTGCTGCTGAAGGTCATGGATGCCAAGCACAAGAACTGCATGGAGTCATTCCTGGAAGCAGCGAGCTTGATGAGCCAAGTGTCGTACCGGCATCTCGTGCTGCTCCACGGCGTGTGCATGGCTGGAGACAGCACCATGGTGCAGGAATTTGTACACCTGGGGGCCATAGACATGTATCTGCGAAAACGTGGCCACCTGGTGCCAGCCAGCTGGAAGCTGCAGGTGGTCAAACAGCTGGCCTACGCCCTCAACTATCTGGAGGACAAAGGCCTGCCCCATGGCAATGTCTCTGCCCGGAAGGTGCTCCTGGCTCGGGAGGGGGCTGATGGGAGCCCGCCCTTCATCAAGCTGAGTGACCCTGGGGTCAGCCCCGCTGTGTTAAGCCTGGAGATGCTCACCGACAGGATCCCCTGGGTGGCCCCCGAGTGTCTCCGGGAGGCGCAGACACTTAGCTTGGAAGCTGACAAGTGGGGCTTCGGCGCCACGGTCTGGGAAGTGTTTAGTGGCGTCACCATGCCCATCAGTGCCCTGGATCCTGCTAAGAAACTCCAATTTTATGAGGACCGGCAGCAGCTGCCGGCCCCCAAGTGGACAGAGCTGGCCCTGCTGATTCAACAGTGCATGGCCTATGAGCCGGTCCAGAGGCCCTCCTTCCGAGCCGTCATTCGTGACCTCAATAGCCTCATCTCTTCAGACTATGAGCTCCTCTCAGACCCCACACCTGGTGCCCTGGCACCTCGTGATGGGCTGTGGAATGGTGCCCAGCTCTATGCCTGCCAAGACCCCACGATCTTCGAGGAGAGACACCTCAAGTACATCTCACAGCTGGGCAAGGGCAACTTTGGCAGCGTGGAGCTGTGCCGCTATGACCCGCTAGGCGACAATACAGGTGCCCTGGTGGCCGTGAAACAGCTGCAGCACAGCGGGCCAGACCAGCAGAGGGACTTTCAGCGGGAGATTCAGATCCTCAAAGCACTGCACAGTGATTTCATTGTCAAGTATCGTGGTGTCAGCTATGGCCCGGGCCGCCAGAGCCTGCGGCTGGTCATGGAGTACCTGCCCAGCGGCTGCTTGCGCGACTTCCTGCAGCGGCACCGCGCGCGCCTCGATGCCAGCCGCCTCCTTCTCTATTCCTCGCAGATCTGCAAGGGCATGGAGTACCTGGGCTCCCGCCGCTGCGTGCACCGCGACCTGGCCGCCCGAAACATCCTCGTGGAGAGCGAGGCACACGTCAAGATCGCTGACTTCGGCCTAGCTAAGCTGCTGCCGCTTGACAAAGACTACTACGTGGTCCGCGAGCCAGGCCAGAGCCCCATTTTCTGGTATGCCCCCGAATCCCTCTCGGACAACATCTTCTCTCGCCAGTCAGACGTCTGGAGCTTCGGGGTCGTCCTGTACGAGCTCTTCACCTACTGCGACAAAAGCTGCAGCCCCTCGGCCGAGTTCCTGCGGATGATGGGATGTGAGCGGGATGTCCCCGCCCTCTGCCGCCTCTTGGAACTGCTGGAGGAGGGCCAGAGGCTGCCGGCGCCTCCTGCCTGCCCTGCTGAGGTTCACGAGCTCATGAAGCTGTGCTGGGCCCCTAGCCCACAGGACCGGCCATCATTCAGCGCCCTGGGCCCCCAGCTGGACATGCTGTGGAGCGGAAGCCGGGGGTGTGAGACTCATGCCTTCACTGCTCACCCAGAGGGCAAACACCACTCCCTGTCCTTTTCATAG"
            ),
            "mutations": [
                ("Pro132Thr", 394, 396),
                ("Arg222His", 664, 666),
                ("Met511Ile", 1531, 1533),
                ("Ala572Val", 1714, 1716),
                ("Ala573Val", 1717, 1719),
                ("Arg657Gln", 1969, 1971),
                ("Val722Ile", 2164, 2166),
                ("Arg840Cys", 2518, 2520),
                ("Arg925Ser", 2773, 2775),
            ],
        },
        "TYK2": {
            "sequence": (
                "ATGCCTCTGCGCCACTGGGGGATGGCCAGGGGCAGTAAGCCCGTTGGGGATGGAGCCCAGCCCATGGCTGCCATGGGAGGCCTGAAGGTGCTTCTGCACTGGGCTGGTCCAGGCGGCGGGGAGCCCTGGGTCACTTTCAGTGAGTCATCGCTGACAGCTGAGGAAGTCTGCATCCACATTGCACATAAAGTTGGTATCACTCCTCCTTGCTTCAATCTCTTTGCCCTCTTCGATGCTCAGGCCCAAGTCTGGTTGCCCCCAAACCACATCCTAGAGATCCCCAGAGATGCAAGCCTGATGCTATATTTCCGCATAAGGTTTTATTTCCGGAACTGGCATGGCATGAATCCTCGGGAACCGGCTGTGTACCGTTGTGGGCCCCCAGGAACCGAGGCATCCTCAGATCAGACAGCACAGGGGATGCAACTCCTGGACCCAGCCTCATTTGAGTACCTCTTTGAGCAGGGCAAGCATGAGTTTGTGAATGACGTGGCATCACTGTGGGAGCTGTCGACCGAGGAGGAGATCCACCACTTTAAGAATGAGAGCCTGGGCATGGCCTTTCTGCACCTCTGTCACCTCGCTCTCCGCCATGGCATCCCCCTGGAGGAGGTGGCCAAGAAGACCAGCTTCAAGGACTGCATCCCGCGCTCCTTCCGCCGGCATATCCGGCAGCACAGCGCCCTGACCCGGCTGCGCCTTCGGAACGTCTTCCGCAGGTTCCTGCGGGACTTCCAGCCGGGCCGACTCTCCCAGCAGATGGTCATGGTCAAATACCTAGCCACACTCGAGCGGCTGGCACCCCGCTTCGGCACAGAGCGTGTGCCCGTGTGCCACCTGAGGCTGCTGGCCCAGGCCGAGGGGGAGCCCTGCTACATCCGGGACAGTGGGGTGGCCCCTACAGACCCTGGCCCTGAGTCTGCTGCTGGGCCCCCAACCCACGAGGTGCTGGTGACAGGCACTGGTGGCATCCAGTGGTGGCCAGTAGAGGAGGAGGTGAACAAGGAGGAGGGTTCTAGTGGCAGCAGTGGCAGGAACCCCCAAGCCAGCCTGTTTGGGAAGAAGGCCAAGGCTCACAAGGCAGTCGGCCAGCCGGCAGACAGGCCGCGGGAGCCACTGTGGGCCTACTTCTGTGACTTCCGGGACATCACCCACGTGGTGCTGAAAGAGCACTGTGTCAGCATCCACCGGCAGGACAACAAGTGCCTGGAGCTGAGCTTGCCTTCCCGGGCTGCGGCGCTGTCCTTCGTGTCGCTGGTGGACGGCTATTTCCGCCTGACGGCCGACTCCAGCCACTACCTGTGCCACGAGGTGGCTCCCCCACGGCTGGTGATGAGCATCCGGGATGGGATCCACGGACCCCTGCTGGAGCCATTTGTGCAGGCCAAGCTGCGGCCCGAGGACGGCCTGTACCTCATTCACTGGAGCACCAGCCACCCCTACCGCCTGATCCTCACAGTGGCCCAGCGTAGCCAGGCACCAGACGGCATGCAGAGCTTGCGGCTCCGAAAGTTCCCCATTGAGCAGCAGGACGGGGCCTTCGTGCTGGAGGGCTGGGGCCGGTCCTTCCCCAGCGTTCGGGAACTTGGGGCTGCCTTGCAGGGCTGCTTGCTGAGGGCCGGGGATGACTGCTTCTCTCTGCGTCGCTGTTGCCTGCCCCAACCAGGAGAAACCTCCAATCTCATCATCATGCGGGGGGCTCGGGCCAGCCCCAGGACACTCAACCTCAGCCAGCTCAGCTTCCACCGGGTTGACCAGAAGGAGATCACCCAGCTGTCCCACTTGGGCCAGGGCACAAGGACCAACGTGTATGAGGGCCGCCTGCGAGTGGAGGGCAGCGGGGACCCTGAGGAGGGCAAGATGGATGACGAGGACCCCCTCGTGCCTGGCAGGGACCGTGGGCAGGAGCTACGAGTGGTGCTCAAAGTGCTGGACCCTAGTCACCATGACATCGCCCTGGCCTTCTACGAGACAGCCAGCCTCATGAGCCAGGTCTCCCACACGCACCTGGCCTTCGTGCATGGCGTCTGTGTGCGCGGCCCTGAAAATATCATGGTGACAGAGTACGTGGAGCACGGACCCCTGGATGTGTGGCTGCGGAGGGAGCGGGGCCATGTGCCCATGGCTTGGAAGATGGTGGTGGCCCAGCAGCTGGCCAGCGCCCTCAGCTACCTGGAGAACAAGAACCTGGTTCATGGTAATGTGTGTGGCCGGAACATCCTGCTGGCCCGGCTGGGGTTGGCAGAGGGCACCAGCCCCTTCATCAAGCTGAGTGATCCTGGCGTGGGCCTGGGCGCCCTCTCCAGGGAGGAGCGGGTGGAGAGGATCCCCTGGCTGGCCCCCGAATGCCTACCAGGTGGGGCCAACAGCCTAAGCACCGCCATGGACAAGTGGGGGTTTGGCGCCACCCTCCTGGAGATCTGCTTTGACGGAGAGGCCCCTCTGCAGAGCCGCAGTCCCTCCGAGAAGGAGCATTTCTACCAGAGGCAGCACCGGCTGCCCGAGCCCTCCTGCCCACAGCTGGCCACACTCACCAGCCAGTGTCTGACCTATGAGCCAACCCAGAGGCCATCATTCCGCACCATCCTGCGTGACCTCACCCGGCTGCAGCCCCACAATCTTGCTGACGTCTTGACTGTGAACCCGGACTCACCGGCGTCGGACCCTACGGTTTTCCACAAGCGCTATTTGAAAAAGATCCGAGATCTGGGCGAGGGTCACTTCGGCAAGGTCAGCTTGTACTGCTACGATCCGACCAACGACGGCACTGGCGAGATGGTGGCGGTGAAAGCCCTCAAGGCAGACTGCGGCCCCCAGCACCGCTCGGGCTGGAAGCAGGAGATTGACATTCTGCGCACGCTCTACCACGAGCACATCATCAAGTACAAGGGCTGCTGCGAGGACCAAGGCGAGAAGTCGCTGCAGCTGGTCATGGAGTACGTGCCCCTGGGCAGCCTCCGAGACTACCTGCCCCGGCACAGCATCGGGCTGGCCCAGCTGCTGCTCTTCGCCCAGCAGATCTGCGAGGGCATGGCCTATCTGCACGCGCAGCACTACATCCACCGAGACCTAGCCGCGCGCAACGTGCTGCTGGACAACGACAGGCTGGTCAAGATCGGGGACTTTGGCCTAGCCAAGGCCGTGCCCGAAGGCCACGAGTACTACCGCGTGCGCGAGGATGGGGACAGCCCCGTGTTCTGGTATGCCCCAGAGTGCCTGAAGGAGTATAAGTTCTACTATGCGTCAGATGTCTGGTCCTTCGGGGTGACCCTGTATGAGCTGCTGACGCACTGTGACTCCAGCCAGAGCCCCCCCACGAAATTCCTTGAGCTCATAGGCATTGCTCAGGGTCAGATGACAGTTCTGAGACTCACTGAGTTGCTGGAACGAGGGGAGAGGCTGCCACGGCCCGACAAATGTCCCTGTGAGGTCTATCATCTCATGAAGAACTGCTGGGAGACAGAGGCGTCCTTTCGCCCAACCTTCGAGAACCTCATACCCATTCTGAAGACAGTCCATGAGAAGTACCAAGGCCAGGCCCCTTCAGTGTTCAGCGTGTGCTGA"
            ),
            "mutations": [
                ("Arg231Trp", 691, 693),
                ("Val362Phe", 1084, 1086),
                ("Gly634Glu", 1900, 1902),
                ("Ile684Ser", 2050, 2052),
                ("Arg703Trp", 2107, 2109),
                ("Gly761Val", 2281, 2283),
                ("Ala928Val", 2782, 2784),
                ("Pro1104Ala", 3310, 3312),
            ],
        },
    }




    # ------------------------------------------------------
    # 2. CAS9 VARIANTS (ONLY ONE PER UNIQUE IUPAC)
    # ------------------------------------------------------
    # We'll keep only entries that have a well-defined IUPAC code
    # and do not duplicate the same IUPAC pattern.
    cas_variants = [
        {
            "name": "SpCas9",
            "iupac": "NGG",
            "recognition": "5'-NGG-3'",
        },
        {
            "name": "SaCas9",
            "iupac": "NNGRRT",
            "recognition": "5'-NNGRRT-3'",
        },
        {
            "name": "NmCas9",
            "iupac": "NNNNGATT",
            "recognition": "5'-NNNNGATT-3'",
        },
        {
            "name": "St1Cas9",
            "iupac": "NNAGAAW",
            "recognition": "5'-NNAGAAW-3'",
        },
        {
            "name": "St3Cas9",
            "iupac": "NGGNG",
            "recognition": "5'-NGGNG-3'",
        },
        {
            "name": "CjCas9",
            "iupac": "NNNNACA",
            "recognition": "5'-NNNNACA-3'",
        },
        {
            "name": "FnCas9",
            "iupac": "YG",
            "recognition": "5'-YG-3'",
        },
        {
            "name": "TdCas9",
            "iupac": "NAAAW",
            "recognition": "5'-NAAA(A/T)-3'",
        },
        {
            "name": "SpCas9-NG (SpG)",
            "iupac": "NG",
            "recognition": "5'-NG-3'",
        },
        {
            "name": "SpRY",
            "iupac": "NRN",
            "recognition": "Near-PAM-less (NRN)",
        },
    ]

    # ------------------------------------------------------
    # 3. IUPAC -> REGEX CONVERSION
    # ------------------------------------------------------
    iupac_dict = {
        "A": "A",   "C": "C",   "G": "G",   "T": "T",
        "R": "[AG]","Y": "[CT]","S": "[GC]","W": "[AT]",
        "K": "[GT]","M": "[AC]","B": "[CGT]","D": "[AGT]",
        "H": "[ACT]","V": "[ACG]","N": "[ACGT]"
    }

    def iupac_to_regex(iupac_seq):
        pattern_str = ""
        for char in iupac_seq.upper():
            pattern_str += iupac_dict.get(char, char)  # default: pass char if unknown
        return re.compile(pattern_str)

    # Compile each Cas variant's pattern
    for cas in cas_variants:
        cas["pattern"] = iupac_to_regex(cas["iupac"])

    # ------------------------------------------------------
    # 4. SEARCH FUNCTION
    # ------------------------------------------------------
    def find_pam_sites_in_window(full_seq, start_pos, end_pos, win_size, cas_variant):
        """
        Extract a window around [start_pos..end_pos] (1-based),
        then search for the Cas9 PAM using the compiled regex.
        Return a list of (localStart, localEnd, fullStart, fullEnd).
        """
        seq_len = len(full_seq)
        wstart = max(1, start_pos - win_size)
        wend   = min(seq_len, end_pos + win_size)

        py_start = wstart - 1
        py_end   = wend

        snippet = full_seq[py_start:py_end].upper()

        matches = []
        for m in cas_variant["pattern"].finditer(snippet):
            loc_start = m.start() + 1  # convert to 1-based
            loc_end   = m.end()
            full_start = wstart + loc_start - 1
            full_end   = wstart + loc_end - 1

            matches.append((loc_start, loc_end, full_start, full_end))

        return matches

    # ------------------------------------------------------
    # 5. PROCESS EACH GENE -> OWN FILE
    # ------------------------------------------------------
    for gene_name, info in gene_data.items():
        sequence = info["sequence"].upper()
        mutations = info["mutations"]

        # We'll store hits in a dict: enzyme_hits[casName][mutName] = [ ...positions... ]
        enzyme_hits = {}
        for cas in cas_variants:
            enzyme_hits[cas["name"]] = {
                "iupac": cas["iupac"]
            }

        for (mut_name, start, end) in mutations:
            for cas in cas_variants:
                cas_name = cas["name"]
                hits = find_pam_sites_in_window(sequence, start, end, window_size, cas)
                enzyme_hits[cas_name][mut_name] = hits

        # Build the header
        header_cols = ["Cas_protein", "Recognition"]
        for (mut_name, _, _) in mutations:
            header_cols += [
                mut_name,
                f"{mut_name}_LocalStart",
                f"{mut_name}_LocalEnd",
                f"{mut_name}_FullStart",
                f"{mut_name}_FullEnd",
            ]

        output_filename = outputdirectory+f"{gene_name}.tsv"
        with open(output_filename, "wt", newline="", encoding="utf-8") as out_f:
            writer = csv.writer(out_f, delimiter="\t")
            writer.writerow(header_cols)

            # One row per Cas
            for cas_name in sorted(enzyme_hits.keys()):
                row_data = [cas_name, enzyme_hits[cas_name]["iupac"]]

                # For each mutation in the same order, gather hits
                for (mut_name, _, _) in mutations:
                    pos_list = enzyme_hits[cas_name][mut_name]
                    if not pos_list:
                        # no hits => placeholders
                        row_data += [mut_name, "-", "-", "-", "-"]
                    else:
                        local_starts = ";".join(str(p[0]) for p in pos_list)
                        local_ends   = ";".join(str(p[1]) for p in pos_list)
                        full_starts  = ";".join(str(p[2]) for p in pos_list)
                        full_ends    = ";".join(str(p[3]) for p in pos_list)

                        row_data += [
                            mut_name,
                            local_starts,
                            local_ends,
                            full_starts,
                            full_ends
                        ]

                writer.writerow(row_data)

        print(f"Created file: {output_filename}")

    print("All done!")


if __name__ == "__main__":
    main()
